export const ApiUrls:any={
    dispatcher:{
        getAll:"dispatcher/all",
        delete:"dispatcher/delete",
        add:"dispatcher/signup",
        update:"dispatcher/update"
    },
    roles:{
        all:"roles/all",
        create:"roles/create",
        update:"roles/update",
        delete:"roles/delete"
    },
    customer_login:{
        all:"customer_login/all",
        signup:"customer_login/signup",
        delete:"customer_login/delete",
        update:"customer_login/update",
        login:"customer_login/login"
    },
    timesheet:{
        all:"timehsheet/all"
    },
    ride:{
        declineRides:"ride/declined_rides",
        updateComments:"ride/updateride_comments"
    },
    cust_comment:{
        add:"cust_comment/add",
        get_ride:"cust_comment/ride/"
    },
    car:{
        getCar:"car/{id}",
        getCarsUnderDispatcher:"car/fetch?dispatcher_id="
    },
    driver:{
        id:"driver/auth/{id}",
        getAll:"driver/fetch?dispatcher_id="
    },
    dispatcherScheduler:{
       getSchedulers:"dispSch/fetchByDispatcher/"
    }
}

export const Mesages={
    password:"@123456"
}